name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Get repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo "${GITHUB_REPOSITORY#*/}" | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: Set image tag
        id: set_image_tag
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --tag ${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_TAG }}